services:
  igpt:
    build: .
    image: "igpt"
    container_name: "igpt"
    restart: "unless-stopped"
    ports:
      - "7862:7862"
    volumes:
      - /path/to/model_zoo:/InternGPT/model_zoo
      - /path/to/certificate:/InternGPT/certificate
    entrypoint: "python"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command:
      - "-u"
      - "app.py"
      - "--load"
      - "StyleGAN_cuda:0"
      - "--tab"
      - "DragGAN"
      - "--https"
